# Generated by Django 5.2.5 on 2026-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='is_verified_traveler',
            field=models.BooleanField(default=False, help_text='Verified by college ID'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image for AI matching', null=True, upload_to='lost_found/'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='location',
            field=models.CharField(help_text='Where was it lost/found?', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='category',
            field=models.CharField(choices=[('book', 'Books'), ('cycle', 'Cycles'), ('electronics', 'Electronics'), ('garbage', 'Garbage to College (Scrap/Recycle)'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='description',
            field=models.TextField(help_text='Condition, brand, or specific details'),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='file',
            field=models.FileField(blank=True, help_text='Upload PDF/Images', null=True, upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='link',
            field=models.URLField(blank=True, help_text='YouTube/Drive link for videos', null=True),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='resource_type',
            field=models.CharField(choices=[('pyq', 'Previous Year Question (PYQ)'), ('notes', 'Topper Notes'), ('video', 'Video Lecture Link')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studyresource',
            name='subject_code',
            field=models.CharField(help_text='e.g., CS101, MA201', max_length=20),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='capacity',
            field=models.PositiveIntegerField(default=1, help_text='Seats available / People needed'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='contact_info',
            field=models.CharField(help_text='Phone number or WhatsApp link', max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='destination',
            field=models.CharField(help_text='e.g., Chandigarh, Delhi Airport', max_length=100),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='mode',
            field=models.CharField(help_text='Cab, Auto, or Personal Vehicle', max_length=50),
        ),
    ]
