# Generated by Django 5.2.5 on 2026-02-06 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='AI-generated summary of the email/notice')),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('source', models.CharField(help_text="e.g., 'Dean Academics' or 'Estate Office'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], max_length=20)),
                ('dish_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Sides, deserts, etc.')),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date', 'meal_type'],
                'unique_together': {('date', 'meal_type')},
            },
        ),
    ]
